name: geoalbum
description: "Галерея фотографий с геотегами на Flutter"
organization: "com.geoalbum"

publish_to: 'none'

version: 1.8.9+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  exif: ^3.3.0
  path: ^1.9.1
  flutter_map_marker_cluster: ^8.2.2
  provider: ^6.0.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  http: ^1.5.0